## YAML Template.
---
server:
  port: 8089

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    hostname: localhost

spring:
  profiles: test
  boot.admin.client.url: http://localhost:8084
  boot.admin.client.username: admin
  boot.admin.client.password: OpenSpace
  boot.admin.client.instance.metadata.user.name: admin
  boot.admin.client.instance.metadata.user.password: OpenSpace
  application:
    name: user-service
  user:
    datasource:
      url: jdbc:mysql://localhost:3306/optimeyesai_user_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      #username: root
      #password: OpenSpace
      hikari:
        connection-timeout: 50000
        idle-timeout: 300000
        max-lifetime: 900000
        maximum-pool-size: 10
        minimum-idle: 10
        pool-name: ConnPool-User
  authuser:
    datasource:
      url: jdbc:mysql://localhost:3306/optimeyesai_auth_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      #username: root
      #password: OpenSpace
      hikari:
        connection-timeout: 50000
        idle-timeout: 300000
        max-lifetime: 900000
        maximum-pool-size: 10
        minimum-idle: 10
        pool-name: ConnPool-Authuser
  jpa:
    #generate-ddl: true
    #hibernate.ddl-auto: update
    show-sql: true
    hibernate:
      connection:
        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  file:
    name: /home/ubuntu/logs/optimeyesai/test/user-service-test.log
